/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Submission = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'courseSelection' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const SubmitResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'getAdmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'submitAdmission' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [SubmitResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Submission = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'courseSelection' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const SubmitResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  
  return IDL.Service({
    'getAdmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'submitAdmission' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [SubmitResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };