/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Submission {
  'id' : bigint,
  'age' : bigint,
  'courseSelection' : string,
  'name' : string,
  'email' : string,
  'contactNumber' : string,
}
export type SubmitResult = { 'ok' : bigint } |
  { 'err' : string };
export interface _SERVICE {
  'getAdmissions' : ActorMethod<[], Array<Submission>>,
  'submitAdmission' : ActorMethod<
    [string, bigint, string, string, string],
    SubmitResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];